service: ${self:provider.tags.customer}-${self:provider.tags.app}-${self:provider.tags.module}-${self:provider.tags.element}

provider:
  runtime: python3.7
  stage: ${opt:stage}
  region: eu-central-1
  tags:
    customer: talos
    app: insight
    stage: ${opt:stage}
    module: translator
    element: ami
    action: create
  environment:
    sqs_queue_url:
      Fn::ImportValue: talos-sqs-url-snap-insight-translator-${opt:stage}
    stack_name: ${self:provider.tags.app}-${self:provider.tags.module}-${self:provider.tags.action}-${self:provider.tags.element}
    stage: ${opt:stage}
    module: ${self:provider.tags.app}-${self:provider.tags.module}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:*
        - lambda:*
      Resource:
        Fn::ImportValue: talos-dynamodb-arn-insight-module-${opt:stage}

functions:
  createAmi:
    handler: handler.createAmi
